### ISSUE TITLE
install  vmware cloudfoundry fails with  (19: self signed certificate in certificate chain)

### ISSUE THREAD

**Issue by angJohn** [cloudfoundry-attic/bosh-sample-release#9]
# bosh micro deploy /root/stemcells/bosh-stemcell-1504-vsphere-esxi-ubuntu.tgz --update

-bash: root@CF-01:~/deployments#: No such file or directory
root@CF-01:~/deployments/micro01# 
root@CF-01:~/deployments/micro01# Updating `micro01/micro_bosh.yml' to`https://192.168.201.144:25555' (type 'yes' to continue): yes

> Verifying stemcell...
> 
> File exists and readable                                     OK
> 
> Verifying tarball...
> 
> Read tarball                                                 OK
> 
> Manifest exists                                              OK
> 
> Stemcell image file                                          OK
> 
> Stemcell properties                                          OK
> 
> Stemcell info
> ---
> 
> Name:    bosh-vsphere-esxi-ubuntu
> 
> Version: 1504
> 
> Will deploy due to stemcell changes
> 
> at depth 1 - 19: self signed certificate in certificate chain
> 
> Prepare for update
> 
> Delete stemcell                     |                        | 0/5 00:00:00  ETA: --:--:--at depth 1 - 19: self signed certificate in certificate chain
> 
>   delete stemcell (00:00:12)                                                                        
> 
> Done                    5/5 00:00:12                                                                
> 
> Deploy Micro BOSH
> 
>   unpacking stemcell (00:00:04)                                                                     
> 
> Uploading stemcell                  |oo                      | 1/11 00:00:15  ETA: 00:00:35at depth 1 - 19: self signed certificate in certificate chain
> 
> Uploading stemcell                  |oo                      | 1/11 00:00:20  ETA: 00:00:30at depth 0 - 20: unable to get local issuer certificate
> 
> Uploading stemcell                  |oo                      | 1/11 00:00:47  ETA: 00:00:03at depth 1 - 19: self signed certificate in certificate chain
> 
>   uploading stemcell (00:01:38)                                                                     
> 
> Creating VM from...                 |oooo                    | 2/11 00:03:59  ETA: 00:05:25at depth 1 - 19: self signed certificate in certificate chain
> 
> Creating VM from...                 |oooo                    | 2/11 00:04:15  ETA: 00:05:09/usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:764:in `block in generate_network_env': undefined method`pop' for nil:NilClass (NoMethodError)
> 
> microfrom /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:761:in `each'
> 
> microfrom /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:761:in `generate_network_env'

how to do it?

yml file:

name: micro01
network:
  ip: 192.168.201.144
  netmask: 255.255.255.128
  gateway: 192.168.201.129
dns:
- 8.8.8.8
- 202.119.32.12
  cloud_properties:
  name: CF Network

cloud:
  plugin: vsphere
  properties:
    agent:
      ntp:
       - time.bnu.edu.cn
       - ntp02.las01.emcatmos.com
    vcenters:
      - host: 10.10.10.100
        user: root
        password: vmware
        datacenters:
          - name: F1-15-A01R
            vm_folder: CF_VMs
            template_folder: CF_Templates
            disk_path: BoshDeployer01
            datastore_pattern: NFSdataStore
            persistent_datastore_pattern: NFSdataStore
            allow_mixed_datastores: true
            clusters:
              - CFCluster
~

**Comment by caseymct** [comment]
hi angJohn,

The network "name" property in the manifest yml has to match a vSphere Network name. You have "CF Network" in the manifest, so you need to verify that there is a corresponding one in vSphere.

There is also a [bosh users google group](https://groups.google.com/a/cloudfoundry.org/forum/#!forum/bosh-users) that can be helpful in these situations.

thanks!
~ @julz and @caseymct

**Comment by angJohn** [comment]
I checked it in vSpphere, CF Network was setted in network.
I havn't resolve this issue. Any other suggestion?
Thanks!

**Comment by angJohn** [comment]
1/11 00:00:27  ETA: 00:00:39at depth 0 - 20: unable to get local issuer certificate
  uploading stemcell (00:01:48)  
Creating VM from...                 |oooo                    | 2/11 00:04:07  ETA: 00:06:25at depth 1 - 19: self signed certificate in certificate chain
Creating VM from...                 |oooo                    | 2/11 00:04:15  ETA: 00:06:17/usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:764:in `block in generate_network_env': undefined method`pop' for nil:NilClass (NoMethodError)
 from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:761:in `each'
 from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:761:in`generate_network_env'
 from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_vsphere_cpi-1.5.0.pre.1492/lib/cloud/vsphere/cloud.rb:247:in `block in create_vm'
 from /usr/local/rvm/gems/ruby-2.0.0-p353/gems/bosh_common-1.5.0.pre.1492/lib/common/thread_formatter.rb:46:in`with_thread_name'

 network_env = {}
      networks.each do |network_name, network|
        network_entry = network.dup
        v_network_name = network['cloud_properties']['name']
        nic = nics[v_network_name].pop
        network_entry['mac'] = nic.mac_address
        network_env[network_name] = network_entry
      end
      network_env
    end

undefined method `pop' for nil????
Thanks!

**Comment by caseymct** [comment]
Hi @angJohn,

The error 
`undefined method 'pop' for nil:NilClass (NoMethodError)` 
is coming from 

```
v_network_name = network['cloud_properties']['name']
nic = nics[v_network_name].pop
```

since nics[v_network_name] is undefined, since this network does not have hash keys ['cloud_properties']['name'].

I can't exactly tell from your yml file, but the indentation should look like this:

```
network:
  ip: 192.168.201.144
  netmask: 255.255.255.128
  gateway: 192.168.201.129
  dns:
  - 8.8.8.8
  - 202.119.32.12
  cloud_properties:
    name: CF Network
```

Can you check to see that the indentation is correct and cloud_properties is nested underneath networks?
If that still does not work, try the bosh users google group linked above.

thanks!
~ @caseymct

**Comment by angJohn** [comment]
root@CF-01:~/deployments# bosh micro status
Stemcell CID   sc-6ed7cb9d-5c74-4c61-84d2-82f1665d3cc7
Stemcell name  bosh-stemcell-1525-vsphere-esxi-ubuntu
VM CID         vm-182d7fa6-c3e3-4dca-bd17-5c37583011a5
Disk CID       disk-0ee7eb91-710f-446d-892d-d5e4474fe84e
Micro BOSH CID bm-0cab24bb-4a63-47ff-bd6e-ad9c7aef9817
Deployment     /root/deployments/micro01/micro_bosh.yml
Target         https://192.168.201.145:25555
root@CF-01:~/deployments# ls

thanks!

yanghu

**Comment by caseymct** [comment]
@angJohn looks like this issue is resolved for you then? Closing, please re-open if you're still having trouble.
